package com.juwan;

import java.util.*;

public class Game {

    public int startGame() {
        Scanner scanner = new Scanner(System.in); // get input

        int rock = 1;
        int paper = 2;
        int scissors = 3;

        int player; //user
        int cpu; // cpu

        //create a variable to hold the user response using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)
        player = scanner.nextInt();
        cpu = scanner.nextInt(3); // max 3 options

        // create a variable to hold the cpu response generated by the getCPUResponse() method.

        //compare user and cpu response with each other to decide the winner.

        if (player == cpu) {
            System.out.println("No winner");
        }
        if ((player == rock && cpu == scissors) || (player == scissors && cpu == paper) || (player == paper && cpu == rock)) // all winning options
        {
            System.out.println("you won");
        } else {
            System.out.println("you lose");

        }

        public int getCPUResponse() {
            Random choose = new Random(); // get random number

            // Generate random integers in range 1 to 3

            new Random().nextInt(4);

        }
    }
}